---
- name: Halt
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Halt molecule instance(s) # noqa fqcn[action]
      vagrant:
        instances: "{{ molecule_yml.platforms }}"
        limit_to_instance: "{{ lookup('env', 'MOLECULE_HOST') | default(omit, true) }}"
        default_box: "{{ molecule_yml.driver.default_box | default('generic/alpine316') }}"
        provider_name: "{{ molecule_yml.driver.provider.name | default(omit, true) }}"
        cachier: "{{ molecule_yml.driver.cachier | default(omit) }}"
        force_stop: "{{ molecule_yml.driver.force_stop | default(false) }}"
        state: halt
      register: server
      no_log: false
